name = "spin-macho-casino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-macho-casino.pt"
HMAC_KEY = "72b75b478936930fd0d6a3557df308c16b012dd8f3da2170cc534a163885f2c2"
COOKIE_NAME = "8ba"
PLAY_PATH = "discover"
BUTTON_ID = "paf597318f2f952aa1ca1f8110455ff12"
GATE_SALT = "84d7c77978e33c34"
